#!/bin/bash

while getopts ":f:" flag;
do
  case "${flag}" in
    f) fmt=${OPTARG};;
  esac
done

if [ $fmt == "" ]
then
  echo "You seem to have not set an output format please use -e with a type eg (mkv, mp4)"
fi

for file in $@;
do
  ffmpeg -i "$file" -vf scale=-1:1080 -c:v libx265 -crf 28 -preset:v veryfast -c:a aac -q:a 1 "${file%.*}.$fmt";
done
