#!/bin/bash

while getopts ":f:" flag;
do
  case "${flag}" in
    f) fmt=${OPTARG};;
  esac
done

if [ $fmt == "" ]
then
  echo "You seem to have not set an output format please use -e with a type eg (mkv, mp4)"
fi

for file in $@;
do
  ffmpeg -i "$file" -vf scale=-1:1440 -c:v libx264 -crf 22 -preset:v slow -c:a aac -q:a 3 "${file%.*}.$fmt";
done
