#!/bin/bash

while getopts f flag
do
  case "${flag}" in
    f) fmt=${OPTARG};;
  esac
done

if [ $fmt == "" ]
then
  echo "You seem to have not set an output format please us -e with a type eg (mkv, mp4)"
fi

for file in $@;
do
  ffmpeg -i "$file" -vf scale=-1:720 -c:v libx264 -crf 24 -preset:v slow -c:a aac -q:a 3 "${file%.*}.$fmt";
done
